#!/bin/sh

CACHE_DIR="${XDG_CACHE_HOME:-/home/sam/.cache}"
CACHE_PATH="$CACHE_DIR/covid_data.csv"
SMA_FILENAME="sma.csv"

PDF_CACHE_PATH="$CACHE_DIR/covid_plot.pdf"

wdir="$(mktemp -d)"
cp "$CACHE_PATH" "$wdir/$SMA_FILENAME"
pdf_file="$wdir/plot.pdf"

CASES_COL="blue"
DEATH_COL="red"

# Linits for the x-axis
DATE_MIN=$(date -d "-6 months" -I)
DATE_MAX=$(date -d "+2 days" -I)

# The limits for the y-axes
CASES_MIN=0
CASES_MAX=80000
DEATHS_MIN=0
DEATHS_MAX=200

DATEF=1         # Date              Field
CASESF=2        # Cases             Field (daily cases)
DEATHSF=3       # Deaths            Field (daily deaths)
AVGCASESF=4     # Average Cases     Field
AVGDEATHSF=5    # Average Deaths    Field

MAXC_LASTMONTH=$(tail -n60 "$wdir/$SMA_FILENAME" | cut -d, -f"$CASESF" | sort -nr | head -n1)
MAXD_LASTMONTH=$(tail -n60 "$wdir/$SMA_FILENAME" | cut -d, -f"$DEATHSF" | sort -nr | head -n1)
CASES_MAX=$(( (3*MAXC_LASTMONTH/2000) * 1000 ))
DEATHS_MAX=$(( (3*MAXD_LASTMONTH/20) * 10 ))

TODAY="$(cut -d, -f"$DATEF" "$wdir/$SMA_FILENAME" | tac | grep -m1 .)"
AVGCASES="$(cut -d, -f"$AVGCASESF" "$wdir/$SMA_FILENAME" | tac | grep -m1 . | numfmt --grouping)"
AVGDEATH="$(cut -d, -f"$AVGDEATHSF" "$wdir/$SMA_FILENAME" | tac | grep -m1 . | numfmt --grouping)"

#FIRSTDATE="$(tail -n"$AVG_LEN" "$DB_DIR/$DB_FILENAME" | head -n1 | cut -d, -f"$DATEF")"
#FSTCASES="$(grep "$FIRSTDATE" "$wdir/$SMA_FILENAME" | cut -d, -f"$CASESF" | numfmt --grouping)"
#FSTDEATH="$(grep "$FIRSTDATE" "$wdir/$SMA_FILENAME" | cut -d, -f"$DEATHSF" | numfmt --grouping)"

cd "$wdir" || exit 1

echo "
    set datafile separator ','
    set key autotitle columnhead
    set xdata time
    set timefmt '%Y-%m-%d'
    set format x '%b'
    set grid
    set xtics '$DATE_MIN',2592000 nomirror
    set ytics nomirror textcolor rgb '$CASES_COL'
    set y2tics nomirror textcolor rgb '$DEATH_COL'
    set xrange ['$DATE_MIN':'$DATE_MAX']
    set yrange [$CASES_MIN:$CASES_MAX]
    set y2range [$DEATHS_MIN:$DEATHS_MAX]
    set obj 1 rect from graph 0.01,0.01 to character 18.1,4.8 front fillstyle solid noborder
    set label 10 '$TODAY' at graph 0,0 font 'arial,11' offset character 1.2,2.4 front
    set label 11 '$AVGCASES' at graph 0,0 font 'arial,11' tc rgb '$CASES_COL' offset character 1.2,1.7 front
    set label 12 '$AVGDEATH' at graph 0,0 font 'arial,11' tc rgb '$DEATH_COL' offset character 1.2,1.0 front
    set term pdf color font 'arial,14' linewidth 2
    set output '$pdf_file'
    plot '$SMA_FILENAME' using $DATEF:$AVGCASESF with lines axis x1y1 lt rgb '$CASES_COL', \
    '' using $DATEF:$AVGDEATHSF with lines axis x1y2 lt rgb '$DEATH_COL', \
    '' using $DATEF:$CASESF with dots axis x1y1 lt rgb '$CASES_COL', \
    '' using $DATEF:$DEATHSF with dots axis x1y2 lt rgb '$DEATH_COL'
    " | gnuplot

cp "$pdf_file" "$PDF_CACHE_PATH"
rm -rf "$wdir"
