#!/bin/sh

XDG_DATA_HOME=${XDG_DATA_HOME:-"$HOME/.local/share"}

DB_DIR="$XDG_DATA_HOME"
DB_FILENAME="dbcorona"

SMA_AWKSCRIPT="/home/sam/.scripts/visualise-covid-sma.awk"
SMA_FILENAME="sma.csv"

AVG_LEN=7

wdir="$(mktemp -d)"
awk -F, -f "$SMA_AWKSCRIPT" -v "avg_size=$AVG_LEN" \
    "$DB_DIR/$DB_FILENAME" > "$wdir/$SMA_FILENAME"
pdf_file="$wdir/plot.pdf"

CASES_COL="blue"
DEATH_COL="red"

# Linits for the x-axis
DATE_MIN=$(date -d "-6 months" -I)
DATE_MAX=$(date -d "+2 days" -I)

# The limits for the y-axes
CASES_MIN=0
CASES_MAX=80000
DEATHS_MIN=0
DEATHS_MAX=200

DATEF=1         # Date              Field
CASESF=2        # Cases             Field (daily cases)
DEATHSF=3       # Deaths            Field (daily deaths)
AVGCASESF=4     # Average Cases     Field
AVGDEATHSF=5    # Average Deaths    Field

LASTWEEK="$(date -I -d '-7 days')"

#TODAY="$(tail -n1 "$wdir/$SMA_FILENAME" | cut -d, -f1)"
#AVGCASES="$(tail -n1 "$wdir/$SMA_FILENAME" | cut -d, -f"$AVGCASESF")"
#AVGDEATH="$(tail -n1 "$wdir/$SMA_FILENAME" | cut -d, -f"$AVGDEATHSF")"

FSTCASES="$(grep "$LASTWEEK" "$wdir/$SMA_FILENAME" | cut -d, -f"$CASESF")"
FSTDEATH="$(grep "$LASTWEEK" "$wdir/$SMA_FILENAME" | cut -d, -f"$DEATHSF")"

cd "$wdir" || exit 1

echo "
    set datafile separator ','
    set key autotitle columnhead
    set xdata time
    set timefmt '%Y-%m-%d'
    set format x '%b'
    set grid
    set xtics '$DATE_MIN',2592000 nomirror
    set ytics nomirror textcolor rgb '$CASES_COL'
    set y2tics nomirror textcolor rgb '$DEATH_COL'
    set xrange ['$DATE_MIN':'$DATE_MAX']
    set yrange [$CASES_MIN:$CASES_MAX]
    set y2range [$DEATHS_MIN:$DEATHS_MAX]
    set obj 1 rect from graph 0.01,0.01 to graph 0.12,0.14 front fillstyle solid noborder
    set label 10 '$FSTCASES' at graph 0,0 font 'arial,11' tc rgb '$CASES_COL' offset character 1.2,1.7 front
    set label 11 '$FSTDEATH' at graph 0,0 font 'arial,11' tc rgb '$DEATH_COL' offset character 1.2,1.0 front
    set term pdf color font 'arial,14' linewidth 2
    set output '$pdf_file'
    plot '$SMA_FILENAME' using $DATEF:$AVGCASESF with lines axis x1y1 lt rgb '$CASES_COL', \
    '' using $DATEF:$AVGDEATHSF with lines axis x1y2 lt rgb '$DEATH_COL', \
    '' using $DATEF:$CASESF with dots axis x1y1 lt rgb '$CASES_COL', \
    '' using $DATEF:$DEATHSF with dots axis x1y2 lt rgb '$DEATH_COL'
    " | gnuplot # --persist

setsid -f sh -c "zathura $pdf_file; rm -rf $wdir"
